# -*- coding: utf-8 -*-
import json
import os

SECTIONS = {k: {} for k in ["elements", "moods", "environments", "weather", "times", "dreamTypes", "colors", "styles"]}

def add(section, cid, ar, en, terms, implies=""):
    SECTIONS[section][cid] = {
        "ar": ar, 
        "en": en, 
        "terms": [t for t in terms.split("|") if t], 
        "implies": implies.split() if implies else []
    }

E = lambda *a: add("elements", *a)
M = lambda *a: add("moods", *a)
V = lambda *a: add("environments", *a)
W = lambda *a: add("weather", *a)
T = lambda *a: add("times", *a)
D = lambda *a: add("dreamTypes", *a)
C = lambda *a: add("colors", *a)
S = lambda *a: add("styles", *a)

# ---------------- ELEMENTS ----------------
E("stars","النجوم","stars","نجم|نجوم|نجمة|نجمات|نجيمات|star|stars|starry|starlight|starlit","times.night weather.clear")
E("moon","القمر","moon","قمر|أقمار|هلال|بدر|ضوء القمر|قمري|moon|moons|moonlight|lunar|crescent","times.night")
E("sun","الشمس","sun","شمس|شمسي|أشعة الشمس|sun|sunshine|sunlight|solar","times.day weather.clear")
E("clouds","السحب","clouds","سحاب|سحابة|سحب|غيم|غيوم|غمام|غائم|غائمة|cloud|clouds|cloudy","environments.sky")
E("aurora","الشفق القطبي","aurora","شفق قطبي|أورورا|الأضواء الشمالية|aurora|northern lights","environments.polar times.night")
E("galaxy","المجرات","galaxies","مجرة|مجرات|درب التبانة|سديم|سدم|galaxy|galaxies|nebula|milky way","environments.space")
E("planets","الكواكب","planets","كوكب|كواكب|مدار|زحل|المريخ|المشتري|planet|planets|orbit|saturn|mars|jupiter","environments.space")
E("comet","الشهب","comets","مذنب|مذنبات|شهاب|شهب|نيزك|نيازك|comet|comets|meteor|meteors|shooting star","times.night")
E("rainbow","قوس قزح","rainbow","قوس قزح|rainbow|rainbows")
E("fireflies","اليراعات","fireflies","يراعة|يراعات|حباحب|firefly|fireflies","times.night")
E("lightning","البرق","lightning","برق|رعد|صاعقة|صواعق|lightning|thunder","weather.storm")
E("light","الأضواء","lights","ضوء|نور|أضواء|أنوار|مضيء|مضيئة|مضاءة|مضاء|إضاءة|وهج|توهج|متوهج|سطوع|light|lights|lit|glow|glowing|shining|illuminated")
E("shadows","الظلال","shadows","ظل|ظلال|shadow|shadows","moods.mystery")
E("fire","النار","fire","نار|نيران|لهب|ألسنة|شرر|fire|flame|flames|burning","weather.warm")
E("flying","الطيران","flying","طيران|أطير|تطير|يطير|نطير|طرت|طار|تحليق|أحلق|تحلق|يحلق|حلقت|أجنحة|جناح|fly|flying|flew|soar|soaring|wings|glide","environments.sky dreamTypes.flying moods.freedom")
E("balloons","المناطيد","balloons","منطاد|مناطيد|بالون|بالونات|balloon|balloons|airship","environments.sky")
E("birds","الطيور","birds","طائر|طيور|عصفور|عصافير|حمامة|حمام|نسر|نسور|صقر|صقور|غراب|غربان|bird|birds|eagle|falcon|dove|raven")
E("butterflies","الفراشات","butterflies","فراشة|فراشات|butterfly|butterflies")
E("waves","الأمواج","waves","موج|أمواج|موجة|waves|wave","environments.ocean")
E("beach","الشاطئ","beach","شاطئ|شواطئ|ساحل|سواحل|beach|shore|coast|seaside","environments.ocean")
E("lake","البحيرة","lake","بحيرة|بحيرات|بركة|lake|lakes|pond","environments.countryside")
E("river","النهر","river","نهر|أنهار|جدول|river|rivers|stream|creek")
E("waterfall","الشلال","waterfall","شلال|شلالات|waterfall|waterfalls|cascade")
E("island","الجزيرة","island","جزيرة|جزر|أرخبيل|island|islands|archipelago","environments.ocean")
E("coral","المرجان","coral","مرجان|مرجانية|شعاب|coral|reef","environments.underwater")
E("pearl","اللؤلؤ","pearls","لؤلؤ|لؤلؤة|لآلئ|صدف|أصداف|pearl|pearls|shell|shells")
E("harbor","الميناء","harbor","ميناء|موانئ|مرفأ|رصيف|harbor|harbour|port|dock")
E("ship","السفن","ships","سفينة|سفن|مركب|مراكب|قارب|قوارب|زورق|إبحار|أبحر|شراع|ship|ships|boat|boats|sail|sailing","environments.ocean")
E("whales","الحيتان","whales","حوت|حيتان|دلفين|دلافين|whale|whales|dolphin|dolphins","environments.ocean")
E("fish","الأسماك","fish","سمك|أسماك|سمكة|fish")
E("springs","الينابيع","springs","ينبوع|ينابيع|نبع|نافورة|نوافير|fountain|fountains|springs")
E("lighthouse","المنارة","lighthouse","منارة|منائر|فنار|lighthouse")
E("bridges","الجسور","bridges","جسر|جسور|bridge|bridges")
E("ice","الجليد","ice","جليد|جليدي|جليدية|متجمد|متجمدة|ice|icy|frozen|glacier|glaciers","environments.polar weather.snow")
E("trees","الأشجار","trees","شجرة|أشجار|شجر|شجيرات|أغصان|نخلة|نخيل|tree|trees|branches|canopy|palm|palms","environments.forest")
E("flowers","الزهور","flowers","زهرة|زهور|أزهار|زهر|ياسمين|flower|flowers|bloom|blossoms|jasmine")
E("roses","الورود","roses","وردة|ورد|ورود|rose|roses")
E("garden","الحدائق","gardens","حديقة|حدائق|بستان|بساتين|garden|gardens|orchard")
E("meadow","المروج","meadows","مرج|مروج|حقل|حقول|عشب|أعشاب|سهل|سهول|meadow|field|fields|grass","environments.countryside")
E("mushrooms","الفطر","mushrooms","فطر|فطريات|عش الغراب|mushroom|mushrooms")
E("cliffs","المنحدرات","cliffs","جرف|جروف|منحدر|منحدرات|صخور|صخرة|هاوية|cliff|cliffs|rocks","environments.mountains")
E("cave","الكهوف","caves","كهف|كهوف|مغارة|مغارات|cave|caves|cavern","environments.underground")
E("volcano","البركان","volcano","بركان|براكين|حمم|volcano|lava","weather.warm")
E("sand","الرمال","sand","رمل|رمال|رملي|رملية|sand|sandy","environments.desert")
E("dunes","الكثبان","dunes","كثيب|كثبان|dune|dunes","environments.desert")
E("oasis","الواحة","oasis","واحة|واحات|oasis")
E("mirage","السراب","mirage","سراب|mirage")
E("crystals","البلور","crystals","بلور|بلورات|كريستال|كريستالات|ألماس|جواهر|جوهرة|ياقوت|crystal|crystals|diamond|gems|ruby")
E("gold","الذهب","gold","ذهب|ذهبي|ذهبية|gold|golden")
E("stone","الحجر","stone","حجر|أحجار|حجارة|حجري|stone|stones")
E("castle","القلاع","castles","قلعة|قلاع|حصن|حصون|castle|castles|fortress","styles.medieval dreamTypes.fantasy")
E("tower","الأبراج","towers","برج|أبراج|tower|towers|spire")
E("palace","القصور","palaces","قصر|قصور|palace|palaces")
E("doors","الأبواب","doors","باب|أبواب|بوابة|بوابات|مدخل|door|doors|gate|gates|portal|portals")
E("clock","الساعات","clocks","ساعة|ساعات|عقارب|clock|clocks")
E("maze","المتاهة","maze","متاهة|متاهات|maze|labyrinth","dreamTypes.lost")
E("library","المكتبة","library","مكتبة|مكتبات|كتاب|كتب|مخطوطة|مخطوطات|library|books|book|manuscripts")
E("temple","المعابد","temples","معبد|معابد|هيكل|temple|temples|shrine","dreamTypes.spiritual")
E("domes","القباب","domes","قبة|قباب|مئذنة|مآذن|مسجد|مساجد|جامع|dome|domes|minaret|mosque","styles.arabesque")
E("ruins","الآثار","ruins","أطلال|آثار|أنقاض|ruins|relics","environments.ruins")
E("market","السوق","market","سوق|أسواق|بازار|market|bazaar|souk")
E("lanterns","الفوانيس","lanterns","فانوس|فوانيس|مصباح|مصابيح|قنديل|قناديل|شمعة|شموع|lantern|lanterns|lamp|lamps|candle|candles")
E("neon","النيون","neon","نيون|هولوجرام|هولوغرام|لافتات مضيئة|neon|hologram|holograms","environments.futuristic styles.cyberpunk times.night")
E("robots","الروبوتات","robots","روبوت|روبوتات|إنسان آلي|آلي|robot|robots|android|cyborg","environments.futuristic")
E("technology","التقنية","technology","تقنية|تكنولوجيا|تقني|حاسوب|شاشة|شاشات|ذكاء اصطناعي|سايبر|روبوت|روبوتات|آلة|آلات|technology|tech|digital|cyber|machine|machines|ai","environments.futuristic dreamTypes.scifi")
E("energy","الطاقة","energy","طاقة|كهرباء|كهربائي|بطارية|energy|electric|electricity|reactor|plasma")
E("glass","الزجاج","glass","زجاج|زجاجي|زجاجية|glass|glassy","styles.crystalline")
E("mirror","المرايا","mirrors","مرآة|مرايا|انعكاس|انعكاسات|mirror|mirrors|reflection|reflections")
E("train","القطارات","trains","قطار|قطارات|محطة|سكة حديد|مترو|train|trains|station|railway|subway|metro")
E("skyscrapers","ناطحات السحاب","skyscrapers","ناطحة سحاب|ناطحات سحاب|أبراج شاهقة|مباني شاهقة|مباني عالية|skyscraper|skyscrapers|tall buildings","environments.futuristic")
E("mosaics","الفسيفساء","mosaics","فسيفساء|زخارف|زخرفة|نقوش|mosaic|mosaics|ornate|arabesque","styles.arabesque")
E("statues","التماثيل","statues","تمثال|تماثيل|نحت|منحوتات|statue|statues|sculpture")
E("magic","السحر","magic","سحر|سحري|سحرية|سحرة|تعويذة|تعاويذ|magic|magical|wizard|witch|spell|spells|enchanted","environments.realm dreamTypes.fantasy moods.wonder")
E("dragon","التنين","dragons","تنين|تنانين|dragon|dragons","environments.realm dreamTypes.fantasy")
E("giants","العمالقة","giants","عملاق|عمالقة|giant|giants","dreamTypes.fantasy")
E("fairies","الجنيات","fairies","جنية|جنيات|جن|fairy|fairies|elf|elves|pixie","dreamTypes.fantasy")
E("spirits","الأرواح","spirits","شبح|أشباح|روح|أرواح|طيف|أطياف|عفريت|ghost|ghosts|spirit|spirits|phantom","moods.mystery")
E("legends","الأساطير","legends","أسطورة|أساطير|خرافة|حكاية|حكايات|legend|legends|myth|myths|tale|tales","dreamTypes.fantasy")
E("treasure","الكنز","treasure","كنز|كنوز|خزينة|treasure|treasures|chest","dreamTypes.adventure")
E("kings","الملوك","kings","ملك|ملوك|ملكة|أمير|أميرة|سلطان|عرش|تاج|ملكي|king|kings|queen|prince|princess|throne|crown|royal")
E("empire","الإمبراطورية","empire","إمبراطورية|إمبراطوريات|امبراطورية|إمبراطور|empire|emperor|dynasty|kingdom")
E("knights","الفرسان","knights","فارس|فرسان|سيف|سيوف|درع|knight|knights|sword|swords|armor|warrior","dreamTypes.adventure")
E("civilization","الحضارات","civilizations","حضارة|حضارات|تاريخ|تاريخي|عريق|عصور|civilization|history|historic|historical|antique")
E("caravans","القوافل","caravans","قافلة|قوافل|جمل|جمال|خيمة|خيام|بدوي|ناقة|caravan|camel|camels|tent|tents|nomad","environments.desert")
E("music","الموسيقى","music","موسيقى|موسيقي|لحن|ألحان|غناء|أغنية|أغاني|عزف|عود|بيانو|ناي|ترانيم|music|melody|song|songs|piano|violin|singing|harmony")
E("art","الفن","art","فن|فنون|لوحة|لوحات|رسم|فنان|art|painting|paintings|artist")
E("memories","الذكريات","memories","ذكرى|ذكريات|ماضي|طفولة|طفولتي|memory|memories|past|childhood","moods.nostalgia dreamTypes.memory")
E("secrets","الأسرار","secrets","سر|أسرار|لغز|ألغاز|خفي|مخفي|مجهول|secret|secrets|riddle|hidden|puzzle","moods.mystery")
E("sleep","النوم","sleep","نوم|نائم|نعاس|وسادة|سرير|تهويدة|sleep|sleeping|pillow|bed|lullaby","moods.peaceful")
E("heart","القلب","heart","قلب|قلوب|heart|hearts")
E("horses","الخيول","horses","حصان|خيل|خيول|أحصنة|فرس|أفراس|horse|horses|stallion","")

out_dir = "backend/app/data"
os.makedirs(out_dir, exist_ok=True)
out_
